name: secure_messenger
description: A secure messenger app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.5.6
  firebase_messaging: ^14.7.10
  
  # UI
  cupertino_icons: ^1.0.6
  cached_network_image: ^3.3.0
  
  # Media
  image_picker: ^1.0.5
  video_player: ^2.8.1
  
  # Permissions
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true